/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountsRouteImport } from './routes/admin.accounts'
import { Route as AdminApprovalsRouteImport } from './routes/admin.approvals'
import { Route as AdminEconomyRouteImport } from './routes/admin.economy'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminObservabilityRouteImport } from './routes/admin.observability'
import { Route as AdminSecurityRouteImport } from './routes/admin.security'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as ApiAdminSplatRouteImport } from './routes/api/admin/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountsRoute = AdminAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEconomyRoute = AdminEconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)
const AdminObservabilityRoute = AdminObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminSplatRoute = ApiAdminSplatRouteImport.update({
  id: '/api/admin/$',
  path: '/api/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/accounts': typeof AdminAccountsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/economy': typeof AdminEconomyRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/observability': typeof AdminObservabilityRoute
  '/admin/security': typeof AdminSecurityRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/$': typeof ApiAdminSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/accounts'
    | '/admin/approvals'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/live'
    | '/admin/observability'
    | '/admin/security'
    | '/admin/teams'
    | '/admin/'
    | '/api/admin/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/accounts'
    | '/admin/approvals'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/live'
    | '/admin/observability'
    | '/admin/security'
    | '/admin/teams'
    | '/admin'
    | '/api/admin/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/accounts'
    | '/admin/approvals'
    | '/admin/economy'
    | '/admin/events'
    | '/admin/live'
    | '/admin/observability'
    | '/admin/security'
    | '/admin/teams'
    | '/admin/'
    | '/api/admin/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiAdminSplatRoute: typeof ApiAdminSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/accounts': {
      id: '/admin/accounts'
      path: '/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AdminAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/economy': {
      id: '/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AdminEconomyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/observability': {
      id: '/admin/observability'
      path: '/observability'
      fullPath: '/admin/observability'
      preLoaderRoute: typeof AdminObservabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/security': {
      id: '/admin/security'
      path: '/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/$': {
      id: '/api/admin/$'
      path: '/api/admin/$'
      fullPath: '/api/admin/$'
      preLoaderRoute: typeof ApiAdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAccountsRoute: typeof AdminAccountsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminEconomyRoute: typeof AdminEconomyRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminObservabilityRoute: typeof AdminObservabilityRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountsRoute: AdminAccountsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminEconomyRoute: AdminEconomyRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminObservabilityRoute: AdminObservabilityRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiAdminSplatRoute: ApiAdminSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
